### ISSUE TITLE
Issue after 5.1.1 upgrade

### ISSUE THREAD

**Issue by vhafdal** [rgl/elasticsearch-setup#16]
Unable to start service after upgrade 

elasticseatch-stderr

2016-12-20 14:12:48 Commons Daemon procrun stderr initialized
Exception in thread "main"  LUCENE_6_3_0
	at org.elasticsearch.Version.<clinit>(Version.java:102)
	at org.elasticsearch.bootstrap.Bootstrap.<init>(Bootstrap.java:74)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:268)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)

**Comment by rgl** [comment]
Humm that stack trace does not say much. I advise you to uninstall. Reboot. Then delete the installation directory and install again. Let me know how it went.

**Comment by vhafdal** [comment]
Uninstall and delete everything.
Reinstall and replace the configuration file worked to fix the issue.

**Comment by rgl** [comment]
What do you mean "and replace the configuration file"? After reinstall you needed to do anything else?
